#!/usr/bin/env zsh

# Prompt with pretty colours
BLACK="%{"$'\033[01;30m'"%}"
GREEN="%{"$'\033[32m'"%}"
RED="%{"$'\033[01;31m'"%}"
YELLOW="%{"$'\033[33m'"%}"
BLUE="%{"$'\033[34m'"%}"
CYAN="%{"$'\033[01;36m'"%}"
BOLD="%{"$'\033[01;39m'"%}"
NORM="%{"$'\033[00m'"%}"

