#!/usr/bin/env zsh

# Prompt with pretty colours


# let's load colors into our environment, then set them
autoload colors zsh/terminfo
zmodload zsh/terminfo

  if [[ "$terminfo[colors]" -gt 7 ]]; then
      colors
  fi


for COLOR in RED GREEN YELLOW WHITE BLACK BLUE; do
    eval $COLOR='$fg[${(L)COLOR}]'
    eval BRIGHT_$COLOR='$fg_bold[${(L)COLOR}]'
    # Prompt colors
    eval PR_$COLOR='%{$fg[${(L)COLOR}]%}'
    eval PR_BRIGHT_$COLOR='%{$fg_bold[${(L)COLOR}]%}'
    eval PR_BG_$COLOR='%{$bg[${(L)COLOR}]%}'
    eval PR_BG_BRIGHT_$COLOR='%{$bg_bold[${(L)COLOR}]%}'
done

PR_RESET="%{$reset_color%}"
export LS_COLORS='no=00:fi=00:di=00;34;01:ln=00;36:pi=40;33:so=00;35:do=00;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:'
