#!/usr/bin/env zsh

#export LANG=C
#export LC_CTYPE="en_GB.UTF-8"
#export LC_PAPER="en_GB.UTF-8"

export BLOCKSIZE=K
export LESS=-Mi  # Long prompt, ignore case
#export LSCOLORS=ExGxcxdxCxegDxabagacad
export MANWIDTH=80
export PAGER=less
export BROWSER=firefox
export EDITOR=vim

export NNTPSERVER=
export PATH=~/bin:${PATH}

# Needed for ssh-agent and others
if [[ -z "$SSH_AUTH_SOCK" ]]; then
    export SSH_AUTH_SOCK=$HOME/.ssh/ssh-auth-sock.$HOSTNAME
fi

# disable suspend in shell
stty -ixon
