#!/usr/bin/zsh

if [[ "$HOST" == "sabekorlnx05" || "$HOST" == "sabekorlnx06" || "$HOST" == "sabekorlnx07" ]]
then
  export DCM_IP=10.50.203.58
  PATH=/home/steelj99/slickedit2010/bin:$PATH
  alias run='./run.py $DCM_IP noreboot nosettings noxml'
  alias runr='./run.py $DCM_IP nosettings noxml'
  alias vncserver='vncserver -dpi 75 -geometry 1600x1150 -name '$HOST
  alias k='pkill -9 -f makeflash -u steelj99;pkill -9 -f pretty_make -u steelj99'
  alias nk='konsole --script > /dev/null 2>&1 &'
  export VSLICK='-supf /home/steelj99/.slickedit/keyremap'
  export CVSROOT=:pserver:steelj99@sabekorlnx02:/home/cvs/db
  source /usr/local/bin/ChangeMV -q 4
  #xmodmap ./.xmodmap

fi
if [[ "$HOST" == "steelj" ]]
then
	export PATH=/opt/slickedit/bin:$PATH
fi

if [[ "$HOST" == "euphoria" ]]
then
	export PATH=/opt/slickedit/bin:$PATH
  #export LD_LIBRARY_PATH=/home/jef/projects/Spel/SpelCore
fi
if [[ "$HOST" == "lnxemb-kjk-01.cisco.com" ]]
then
  export MIO_IP=10.48.31.238
  alias vncserver='vncserver -geometry 1600x1150'
  PATH=$PATH:/export/linuxtools/embedded/tools/denx/eldk/4.2/bin:/export/linuxtools/embedded/tools/denx/eldk/4.2/sbin:/export/linuxtools/embedded/tools/denx/eldk/4.2/usr/bin/:/home/steelj99/bin/Scripts
  export CVSROOT=:pserver:steelj99@sabekorlnx02:/home/cvs/db
fi
if [[ "$HOST" == "arch" ]]
then
  export DCM_IP=10.50.203.58
  export CVSROOT=:pserver:steelj99@embedded-kjk.cisco.com:/home/cvs/db
  PATH=/opt/slickedit/bin:$PATH
  alias run='./run.py $DCM_IP noreboot nosettings noxml'
  alias runr='./run.py $DCM_IP nosettings noxml'
fi

