#!/usr/bin/zsh

export DCM_IP=

setDcmIp()
{
  DCM_IP_FILE="/home/steelj99/Projects/DCM_IP"
  if [[ -f $DCM_IP_FILE ]]
  then
    export DCM_IP=$(cat $DCM_IP_FILE)
    export MY_DCM_IP=$DCM_IP
  fi
}

if [[ "$HOST" == "lnx-kjk-11" || "$HOST" == "sabekorlnx05" || "$HOST" == "sabekorlnx06" || "$HOST" == "sabekorlnx07" ]]
then
  setDcmIp
  PATH=/home/steelj99/slickedit17/bin:/home/steelj99/binlocal:$PATH
  alias runr='echo "Running:\n$(grep "^rt" rtconfig.txt)\nOn $DCM_IP\nPress Enter to continue..." && read && ./run.py $DCM_IP putoncefile nosettings noxml local'
  alias run='runr noreboot'
  alias vncserver='vncserver -dpi 75 -geometry 1600x1150 -name '$HOST
  alias k='pkill -9 -f makeflash -u steelj99;pkill -9 -f pretty_make -u steelj99'
  alias nk='konsole --script > /dev/null 2>&1 &'
  alias make='make -j8'
  alias gdb='ppc_440-gdb'
  alias vgStrip='ppc_440-objcopy -R .debug_str -R .debug_info -R .debug_macinfo DCM_IO DCM_IO-vg'
  alias makemfp='make -j8 CONFIG=build/mfp-default-config'
  alias makedcm='make -j8 CONFIG=build/dcm-default-config'
  # make all upload
  alias mau='makemfp upload && makedcm upload'
  export CVSROOT=:pserver:steelj99@sabekorlnx02:/home/cvs/db
  source /usr/local/bin/ChangeMV -q 4
  #xmodmap ./.xmodmap

fi
if [[ "$HOST" == "steelj" ]]
then
	export PATH=/opt/slickedit/bin:$PATH
fi

if [[ "$HOST" == "euphoria" ]]
then
	export PATH=/opt/slickedit/bin:$PATH
  #export LD_LIBRARY_PATH=/home/jef/projects/Spel/SpelCore
fi
if [[ "$HOST" == "delirium" ]]
then
	export PATH=/opt/slickedit/bin:$PATH
fi
if [[ "$HOST" == "lnxemb-kjk-01.cisco.com" ]]
then
  export MIO_IP=10.48.30.214
  alias vncserver='vncserver -geometry 1600x1150'
  PATH=/home/steelj99/slickedit2010/bin:/home/steelj99/dotfiles/sabekorbin:$PATH:/export/linuxtools/embedded/tools/denx/eldk/4.2/bin:/export/linuxtools/embedded/tools/denx/eldk/4.2/sbin:/export/linuxtools/embedded/tools/denx/eldk/4.2/usr/bin/:/home/steelj99/bin/Scripts
  export CVSROOT=:pserver:steelj99@sabekorlnx02:/home/cvs/db
  source /usr/local/burke/powerpc/environment-setup
fi
if [[ "$HOST" == "arch" ]]
then
  setDcmIp
  export CVSROOT=:pserver:steelj99@embedded-kjk.cisco.com:/home/cvs/db
  PATH=/opt/slickedit/bin:$PATH:$HOME/bin/ServerScripts.git
  alias run='checkDcmIp && ./run.py $DCM_IP noreboot nosettings noxml'
  alias runr='checkDcmIp && ./run.py $DCM_IP nosettings noxml'
  alias connectLoop='while [ true ]; do ssh $DCM_IP; sleep 5; done'
  alias rs='setDcm.py; reload'
fi
